# Generated by Django 6.0.4 on 2026-04-18 15:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=8, unique=True)),
                ("name", models.CharField(max_length=80, unique=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(blank=True, max_length=24, unique=True)),
                ("weight_kg", models.DecimalField(decimal_places=2, max_digits=8)),
                ("package_count", models.PositiveIntegerField(default=1)),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Baja"),
                            ("normal", "Normal"),
                            ("high", "Alta"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("assigned", "Asignado"),
                            ("in_transit", "En tránsito"),
                            ("delivered", "Entregado"),
                            ("canceled", "Cancelado"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "requested_for",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders_destination",
                        to="logistics.department",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders_origin",
                        to="logistics.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(blank=True, max_length=24, unique=True)),
                ("route_nodes", models.JSONField(default=list)),
                (
                    "total_distance_km",
                    models.DecimalField(decimal_places=2, max_digits=9),
                ),
                (
                    "estimated_fuel_liters",
                    models.DecimalField(decimal_places=2, max_digits=9),
                ),
                (
                    "estimated_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planificado"),
                            ("in_progress", "En progreso"),
                            ("completed", "Completado"),
                            ("canceled", "Cancelado"),
                        ],
                        default="planned",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips_destination",
                        to="logistics.department",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="trips_origin",
                        to="logistics.department",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TripEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("note", models.TextField()),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="logistics.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TripOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistics.order",
                    ),
                ),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="logistics.trip"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="trip",
            name="orders",
            field=models.ManyToManyField(
                related_name="trips",
                through="logistics.TripOrder",
                to="logistics.order",
            ),
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plate", models.CharField(max_length=16, unique=True)),
                ("model", models.CharField(max_length=100)),
                ("capacity_kg", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "fuel_efficiency_km_l",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("cost_per_km", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "current_department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vehicles",
                        to="logistics.department",
                    ),
                ),
            ],
            options={
                "ordering": ["plate"],
            },
        ),
        migrations.AddField(
            model_name="trip",
            name="vehicle",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="trips",
                to="logistics.vehicle",
            ),
        ),
        migrations.CreateModel(
            name="RouteConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=8)),
                ("is_bidirectional", models.BooleanField(default=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections_to",
                        to="logistics.department",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections_from",
                        to="logistics.department",
                    ),
                ),
            ],
            options={
                "ordering": ["origin__name", "destination__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("origin", "destination"),
                        name="uniq_route_connection_direction",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("origin", models.F("destination")), _negated=True
                        ),
                        name="origin_destination_must_differ",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="triporder",
            constraint=models.UniqueConstraint(
                fields=("trip", "order"), name="uniq_trip_order"
            ),
        ),
    ]
