# Generated by Django 6.0.4 on 2026-05-09 16:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0002_driver_trip_driver_vehicle_driver_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="FuelPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "regular_gtq_l",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("8.50"), max_digits=6
                    ),
                ),
                (
                    "super_gtq_l",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("9.20"), max_digits=6
                    ),
                ),
                (
                    "diesel_gtq_l",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("7.80"), max_digits=6
                    ),
                ),
                ("source", models.CharField(default="MEM Guatemala", max_length=120)),
            ],
            options={
                "verbose_name": "Precio de combustible",
            },
        ),
        migrations.AddField(
            model_name="trip",
            name="estimated_fuel_cost_gtq",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="trip",
            name="fuel_price_gtq_l",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
