# Generated by Django 6.0.4 on 2026-07-25 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0005_update_fuel_price_market_rates"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="algorithm",
            field=models.CharField(
                choices=[("dijkstra", "Dijkstra"), ("astar", "A* (A-estrella)")],
                default="dijkstra",
                help_text="Algoritmo de búsqueda de caminos con el que se calculó la ruta.",
                max_length=16,
            ),
        ),
    ]
