# Generated by Django 6.0.4 on 2026-09-29 00:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0005_update_fuel_price_market_rates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('cabecera', 'Cabecera departamental'), ('municipio', 'Municipio'), ('cruce', 'Cruce, salida o frontera')], max_length=10)),
                ('department', models.CharField(choices=[('AV', 'Alta Verapaz'), ('BV', 'Baja Verapaz'), ('CM', 'Chimaltenango'), ('CQ', 'Chiquimula'), ('PR', 'El Progreso'), ('ES', 'Escuintla'), ('GU', 'Guatemala'), ('HU', 'Huehuetenango'), ('IZ', 'Izabal'), ('JA', 'Jalapa'), ('JU', 'Jutiapa'), ('PE', 'Petén'), ('QZ', 'Quetzaltenango'), ('QC', 'Quiché'), ('RE', 'Retalhuleu'), ('SA', 'Sacatepéquez'), ('SM', 'San Marcos'), ('SR', 'Santa Rosa'), ('SO', 'Sololá'), ('SU', 'Suchitepéquez'), ('TO', 'Totonicapán'), ('ZA', 'Zacapa')], max_length=2)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('latitude__gte', 13.5), ('latitude__lte', 18.0), ('longitude__gte', -92.5), ('longitude__lte', -88.0)), name='node_inside_guatemala')],
            },
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('distance_km', models.FloatField()),
                ('duration_free_min', models.FloatField(help_text='t0: minutos sin tráfico (staticDuration de Google).')),
                ('road', models.CharField(blank=True, help_text='Carretera principal, p. ej. CA-1.', max_length=20)),
                ('source', models.CharField(choices=[('google', 'Google Routes API'), ('manual', 'Manual')], default='google', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_in', to='logistics.node')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_out', to='logistics.node')),
            ],
            options={
                'ordering': ['origin__name', 'destination__name'],
            },
        ),
        migrations.CreateModel(
            name='TrafficProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(choices=[('dawn', 'Madrugada (05:00–07:00)'), ('peak_am', 'Pico mañana (07:00–09:00)'), ('mid_morning', 'Media mañana (09:00–12:00)'), ('midday', 'Mediodía (12:00–14:00)'), ('afternoon', 'Tarde (14:00–17:00)'), ('peak_pm', 'Pico tarde (17:00–20:00)'), ('night', 'Noche (20:00–05:00)')], max_length=12)),
                ('day_type', models.CharField(choices=[('weekday', 'Laboral'), ('weekend', 'Fin de semana')], max_length=8)),
                ('multiplier', models.FloatField()),
                ('calibrated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source', models.CharField(default='google_routes', max_length=40)),
                ('edge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traffic_profiles', to='logistics.edge')),
            ],
            options={
                'ordering': ['edge', 'day_type', 'band'],
            },
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.UniqueConstraint(fields=('origin', 'destination'), name='uniq_edge_direction'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.CheckConstraint(condition=models.Q(('origin', models.F('destination')), _negated=True), name='edge_origin_destination_must_differ'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.CheckConstraint(condition=models.Q(('distance_km__gt', 0)), name='edge_distance_positive'),
        ),
        migrations.AddConstraint(
            model_name='edge',
            constraint=models.CheckConstraint(condition=models.Q(('duration_free_min__gt', 0)), name='edge_duration_positive'),
        ),
        migrations.AddConstraint(
            model_name='trafficprofile',
            constraint=models.UniqueConstraint(fields=('edge', 'band', 'day_type'), name='uniq_traffic_profile'),
        ),
        migrations.AddConstraint(
            model_name='trafficprofile',
            constraint=models.CheckConstraint(condition=models.Q(('multiplier__gte', 1.0)), name='traffic_multiplier_gte_1'),
        ),
    ]
