# Generated by Django 6.0.4 on 2026-09-29 00:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0006_node_edge_trafficprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='source',
            field=models.CharField(choices=[('google', 'Google Routes API'), ('manual', 'Manual'), ('estimate', 'Estimado sin conexión')], default='google', max_length=10),
        ),
        migrations.CreateModel(
            name='RouteSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(blank=True, choices=[('dawn', 'Madrugada (05:00–07:00)'), ('peak_am', 'Pico mañana (07:00–09:00)'), ('mid_morning', 'Media mañana (09:00–12:00)'), ('midday', 'Mediodía (12:00–14:00)'), ('afternoon', 'Tarde (14:00–17:00)'), ('peak_pm', 'Pico tarde (17:00–20:00)'), ('night', 'Noche (20:00–05:00)')], max_length=12)),
                ('day_type', models.CharField(blank=True, choices=[('weekday', 'Laboral'), ('weekend', 'Fin de semana')], max_length=8)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('routing_preference', models.CharField(max_length=30)),
                ('status', models.CharField(blank=True, help_text='Vacío = OK; si no, el error de Google.', max_length=40)),
                ('duration_s', models.FloatField(blank=True, null=True)),
                ('static_duration_s', models.FloatField(blank=True, null=True)),
                ('distance_m', models.FloatField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples_in', to='logistics.node')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples_out', to='logistics.node')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'constraints': [models.UniqueConstraint(fields=('origin', 'destination', 'band', 'day_type'), name='uniq_route_sample')],
            },
        ),
    ]
