# Generated by Django 6.0.4 on 2026-09-29 01:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


LEGACY_TO_NEW = {"supervisor": "dispatcher", "operator": "dispatcher"}


def forwards(apps, schema_editor):
    UserProfile = apps.get_model("logistics", "UserProfile")
    for old, new in LEGACY_TO_NEW.items():
        UserProfile.objects.filter(role=old).update(role=new)


def backwards(apps, schema_editor):
    UserProfile = apps.get_model("logistics", "UserProfile")
    UserProfile.objects.filter(role="dispatcher").update(role="supervisor")
    UserProfile.objects.filter(role="driver").update(role="operator")


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_edge_estimate_routesample'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Cuenta con la que el conductor entra a su vista móvil.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('dispatcher', 'Despachador'), ('driver', 'Conductor')], default='dispatcher', max_length=20),
        ),
        migrations.RunPython(forwards, backwards),
    ]
