# Generated by Django 6.0.4 on 2026-09-29 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_orders_address_depot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=24, unique=True)),
                ('departure_at', models.DateTimeField()),
                ('criterion', models.CharField(choices=[('time', 'Más rápida (tráfico)'), ('distance', 'Más corta (km)')], default='time', max_length=10)),
                ('algorithm', models.CharField(default='astar', max_length=16)),
                ('return_to_depot', models.BooleanField(default=True)),
                ('service_min', models.FloatField(default=10)),
                ('driving_minutes', models.FloatField(help_text='Minutos de manejo con el tráfico de cada tramo.')),
                ('total_km', models.FloatField()),
                ('shortest_minutes', models.FloatField(blank=True, help_text='Minutos de la ruta más corta con el mismo tráfico (para el ahorro).', null=True)),
                ('expanded_nodes', models.PositiveIntegerField(default=0)),
                ('finish_at', models.DateTimeField()),
                ('legs', models.JSONField(default=list, help_text='Tramos: nodos, minutos, km, franja.')),
                ('data_source', models.CharField(blank=True, max_length=80)),
                ('status', models.CharField(choices=[('planned', 'Planificada'), ('in_progress', 'En curso'), ('completed', 'Completada'), ('canceled', 'Cancelada')], default='planned', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='logistics.depot')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='logistics.driver')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routes', to='logistics.vehicle')),
            ],
            options={
                'ordering': ['-departure_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('eta', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('delivered', 'Entregado'), ('failed', 'No entregado')], default='pending', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='route_stops', to='logistics.order')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='logistics.route')),
            ],
            options={
                'ordering': ['route', 'sequence'],
                'constraints': [models.UniqueConstraint(fields=('route', 'sequence'), name='uniq_route_stop_sequence'), models.UniqueConstraint(fields=('route', 'order'), name='uniq_route_stop_order')],
            },
        ),
    ]
