# Generated by Django 6.0.4 on 2026-09-29 02:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_route_routestop'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='started_at',
            field=models.DateTimeField(blank=True, help_text='Cuándo el conductor inició la ruta.', null=True),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('traffic', 'Tránsito pesado'), ('accident', 'Accidente'), ('landslide', 'Derrumbe'), ('closure', 'Carretera cerrada')], max_length=12)),
                ('blocked', models.BooleanField(default=False, help_text='True = el tramo no se puede usar (costo infinito).')),
                ('multiplier', models.FloatField(default=1.0, help_text='Penalización extra ≥ 1 si no está bloqueado.')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Vacío = vigente hasta que se resuelva.', null=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('edges', models.ManyToManyField(related_name='incidents', to='logistics.edge')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('route', models.ForeignKey(blank=True, help_text='Ruta desde la que lo reportó el conductor, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='logistics.route')),
            ],
            options={
                'ordering': ['-starts_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RerouteProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_minutes', models.FloatField(help_text='Minutos restantes por la ruta actual, con el incidente.')),
                ('proposed_minutes', models.FloatField(help_text='Minutos restantes por la ruta nueva.')),
                ('proposed_legs', models.JSONField(default=list, help_text='Tramos pendientes recalculados con A*.')),
                ('summary', models.CharField(blank=True, help_text='Ej.: "Nueva ruta por Palín: −18 min".', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptada'), ('kept', 'Mantuvo la ruta'), ('expired', 'Vencida')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('incident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reroutes', to='logistics.incident')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reroutes', to='logistics.route')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.CheckConstraint(condition=models.Q(('multiplier__gte', 1.0)), name='incident_multiplier_gte_1'),
        ),
    ]
