# Generated by Django 6.0.4 on 2026-10-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_incidents_reroutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='road_class',
            field=models.CharField(choices=[('primary', 'Primaria (CA)'), ('secondary', 'Secundaria asfaltada'), ('unpaved', 'Terracería')], default='secondary', help_text='Terracería: el planificador la evita salvo que no haya otra opción.', max_length=10),
        ),
    ]
